name: BlastSpawn
version: 1.0.0
main: com.github.tckz916.blastspawn.BlastSpawn

commands:
    setspawn:
        description:
    currentsettings:
        description:
    spawn:
        description:
permissions:
    blastspawn.command.currentsettings:
        default: op
    blastspawn.command.setspawn:
        default: op
    blastspawn.command.spawn:
            default: op