name: BlastSpawn
version: 1.0.0
main: com.github.tckz916.blastspawn.BlastSpawn

commands:
    setspawn:
        description: SetSpawn Command
        aliases: ss
        permission: blastspawn.command.setspawn
    currentsettings:
        description: CurrentSettings Command
        aliases: cs
        permission: blastspawn.command.currentsettings
    spawn:
        description: Spawn Command
        aliases: [s,hub,lobby]
        permission: blastspawn.command.spawn
permissions:
    blastspawn.command.currentsettings:
        default: op
    blastspawn.command.setspawn:
        default: op
    blastspawn.command.spawn:
        default: true